name: Execute Movie Analysis

on: [push, workflow_dispatch] # This runs it every time you save

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pandas matplotlib seaborn

      - name: Run Analysis
        run: python main.py
